# Generated by Django 4.1.9 on 2023-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricevi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='name',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
