# Generated by Django 4.1.9 on 2023-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richiedente', models.CharField(max_length=50)),
                ('reparto_destinatario', models.CharField(max_length=50)),
                ('reparto_richiedente', models.CharField(max_length=50)),
                ('data_richiesta', models.DateField()),
                ('priorità', models.IntegerField()),
                ('data_evasione_richiesta', models.DateField()),
                ('data_evasione_effettiva', models.DateField()),
                ('descrizione', models.TextField()),
            ],
        ),
    ]
