# Generated by Django 4.1.9 on 2023-05-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Tickets'},
        ),
    ]
