# Generated by Django 4.1.9 on 2023-05-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invia', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
