# Generated by Django 4.1.9 on 2023-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invia', '0003_ticket_note_ticket_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data_evasione_effettiva',
            field=models.DateField(default='2023-5-24'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priorità',
            field=models.CharField(max_length=15),
        ),
    ]
