# Generated by Django 4.1.9 on 2023-05-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invia', '0004_alter_ticket_data_evasione_effettiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data_evasione_effettiva',
            field=models.DateField(default='2023-5-25'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='data_richiesta',
            field=models.DateField(default='2023-5-25'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reparto_destinatario',
            field=models.CharField(default='Logistica', editable=False, max_length=50),
        ),
    ]
