# Generated by Django 4.1.9 on 2023-05-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invia', '0005_alter_ticket_data_evasione_effettiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='titolo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='data_evasione_effettiva',
            field=models.DateField(default='2023-5-26'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='data_richiesta',
            field=models.DateField(default='2023-5-26'),
        ),
    ]
