# Generated by Django 4.1.9 on 2023-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invia', '0006_ticket_titolo_alter_ticket_data_evasione_effettiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.CharField(default='', max_length=20),
        ),
    ]
